server:
  port: 9098
spring:
  thymeleaf:
    prefix:
      classpath: /templates/
  datasource:
    url: jdbc:postgresql://localhost:5432/uav
    username: postgres
    password: root123
    driver-class-name: org.postgresql.Driver
  mvc:
    view:
      prefix: html
  devtools:
    restart:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
